spring:
  datasource:
    url: jdbc:h2:file:./data/productbuilder;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
    cache: false
server:
  port: 8080
